{
 "title": "East/West Analysis",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Power generation: East Panels vs. West Panels",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nfrom(bucket: \"homedata\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /mqtt\\.0\\.solar\\.116183777340\\.[01234]\\.power$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\r\n  |> map(fn: (r) => ({ r with \"East Panels\": r[\"mqtt.0.solar.116183777340.3.power\"] + r[\"mqtt.0.solar.116183777340.4.power\"],\r\n                              \"West Panels\":  r[\"mqtt.0.solar.116183777340.1.power\"] + r[\"mqtt.0.solar.116183777340.2.power\"]\r\n     })) \r\n"
    }
   ]
  },
  {
   "title": "Power per Panel and Total Power",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"homedata\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /mqtt\\.0\\.solar\\.116183777340\\.[01234]\\.power$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\r\n"
    }
   ]
  },
  {
   "title": "DC Voltage per Panel",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"homedata\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /mqtt\\.0\\.solar\\.116183777340\\.[1234]\\.voltage/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\r\n"
    }
   ]
  }
 ]
}