{
 "title": "Energy Flow Overview Copy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Time Range",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# ${__from:date:DD.MM.YYYY HH:mm}  to  ${__to:date:DD.MM.YYYY HH:mm}"
   }
  },
  {
   "title": "Power Sources",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"interpolate\"\r\nimport \"date\"\r\nimport \"math\"\r\n\r\n// using prefix \"m\" for _measurement here\r\nmGrid = \"shelly.0.shellypro3em#0cb815fd0400#1.EM0.TotalActivePower\"\r\nmFromBat = \"mqtt.0.T2SGF72095.ACDISPLAY\"\r\nmToBat = \"mqtt.0.T2MG2CAA11.ACDISPLAY\"\r\nmSolar = \"mqtt.0.solar.116183777340.0.power\"\r\n\r\ntDuration = 3m\r\ntWindow = 1s\r\n\r\nfrom(bucket: \"homedata\")\r\n  |> range(start: duration (v: -int(v: tDuration)))\r\n  |> filter(fn: (r) => r[\"_measurement\"] ==  mToBat or \r\n                       r[\"_measurement\"] == mSolar or \r\n                       r[\"_measurement\"] ==  mGrid or\r\n                       r[\"_measurement\"] == mFromBat)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> interpolate.linear(every: tWindow) \r\n  |> aggregateWindow(every: tWindow, column: \"_value\", fn:last)\r\n  |> fill(usePrevious: true)\r\n  |> last()\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\r\n  |> rename(columns: {\"mqtt.0.T2MG2CAA11.ACDISPLAY\": \"toBatPower\", \r\n                      \"mqtt.0.T2SGF72095.ACDISPLAY\": \"fromBatPower\",\r\n                      \"shelly.0.shellypro3em#0cb815fd0400#1.EM0.TotalActivePower\": \"GridPowerPosNeg\",\r\n                      \"mqtt.0.solar.116183777340.0.power\": \"SolarPower\"})\r\n  |> map(fn: (r) => ({ r with GridPowerPos: if r.GridPowerPosNeg < 0.0 then 0.0 else math.round(x: r.GridPowerPosNeg), \r\n                              GridPowerNeg: if r.GridPowerPosNeg > 0.0 then 0.0 else math.round(x: -r.GridPowerPosNeg)}))\r\n  |> map(fn: (r) => ({ r with consumedPower: r.GridPowerPosNeg + r.SolarPower + r.fromBatPower - r.toBatPower}))\r\n "
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Energy Flow hourwise",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nt0 = date.truncate(t: v.timeRangeStart, unit: 1h)\r\nt1 = v.timeRangeStop\r\n\r\nfrom(bucket: \"homedata_reduced\")\r\n\t|> range(start: t0, stop: t1)\r\n\t|> filter(fn: (r) => r[\"_measurement\"] =~ /cachedEnergyData\\./)\r\n\t|> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n\t|> aggregateWindow(every: 1h, column: \"_value\", fn:first, timeSrc: \"_start\")\r\n\t|> difference(columns: [\"_value\"])\r\n\t|> timeShift(duration: -30m)\r\n\t|> drop(columns: [\"_start\", \"_stop\", \"_field\"])\r\n\t|> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n\t|> map (fn: (r) => ({\r\n\t\t\t\t\t\t\t_time: r._time, \r\n\t\t\t\t\t\t\ttoBatEnergy: -r[\"cachedEnergyData.toBatEnergy\"], \r\n\t\t\t\t\t\t\tfromBatEnergy: r[\"cachedEnergyData.fromBatEnergy\"], \r\n\t\t\t\t\t\t\tGridEnergyPos: r[\"cachedEnergyData.fromGridEnergy\"], \r\n\t\t\t\t\t\t\tGridEnergyNeg: -r[\"cachedEnergyData.toGridEnergy\"], \r\n\t\t\t\t\t\t\tSolarEnergy: r[\"cachedEnergyData.solarEnergy\"],\r\n\t\t\t\t\t\t}))\r\n\t|> map(fn: (r) => ({r with consumedEnergy: -(r.GridEnergyPos + r.GridEnergyNeg + r.SolarEnergy + r.fromBatEnergy + r.toBatEnergy)}))\r\n\t|> sort(columns: [\"_time\"], desc: false)\r\n\t|> yield(name: \"result\")"
    }
   ]
  },
  {
   "title": "Power Flow over Time",
   "type": "timeseries",
   "description": "x-axis time resolution depending on x-axis dispaly range :<br>\n5s: range < 30m<br>\n1m: range < 2h<br>\n5m: range < 6h<br>\n15m: else  ",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"interpolate\"\r\nimport \"date\"\r\n\r\ndt = (int(v:v.timeRangeStop) - int(v:v.timeRangeStart)) / 1000000000\r\ntSlot = if dt < 21600 then (if dt < 7200 then (if dt < 1800 then 5s else 1m) else 5m) else 15m\r\nt = {timeRangeStart: v.timeRangeStart, timeRangeStop: v.timeRangeStop, windowPeriod: tSlot}\r\n\r\n// using prefix \"m\" for _measurement here\r\nmGrid = \"shelly.0.shellypro3em#0cb815fd0400#1.EM0.TotalActivePower\"\r\nmFromBat = \"mqtt.0.T2SGF72095.ACDISPLAY\"\r\nmToBat = \"mqtt.0.T2MG2CAA11.ACDISPLAY\"\r\nmSolar = \"mqtt.0.solar.116183777340.0.power\"\r\n\r\nfrom(bucket: \"homedata\")\r\n  |> range(start: date.sub(d: 2m, from: t.timeRangeStart), stop: date.add(d: 1m, to: t.timeRangeStop))\r\n  |> filter(fn: (r) => r[\"_measurement\"] ==  mToBat or \r\n                       r[\"_measurement\"] == mSolar or \r\n                       r[\"_measurement\"] ==  mGrid or\r\n                       r[\"_measurement\"] == mFromBat)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> interpolate.linear(every: tSlot) \r\n  |> aggregateWindow(every: tSlot, column: \"_value\", fn:mean)\r\n  |> range(start: t.timeRangeStart, stop: t.timeRangeStop)\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\r\n  |> rename(columns: {\"mqtt.0.T2MG2CAA11.ACDISPLAY\": \"toBatPower\", \r\n                      \"mqtt.0.T2SGF72095.ACDISPLAY\": \"fromBatPower\",\r\n                      \"shelly.0.shellypro3em#0cb815fd0400#1.EM0.TotalActivePower\": \"GridPower\",\r\n                      \"mqtt.0.solar.116183777340.0.power\": \"SolarPower\"})\r\n  |> map(fn: (r) => ({ r with consumedPower: r.GridPower + r.SolarPower + r.fromBatPower - r.toBatPower}))"
    }
   ]
  }
 ]
}