{
 "title": "ESP_Unterverteilung",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status",
   "type": "logs",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"homedata\")\r\n\t|> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt.0.unterverteilung.status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  "
    }
   ]
  },
  {
   "title": "Zählerstand Küche",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homedata\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt.0.unterverteilung.küche.count_total\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  },
  {
   "title": "Zählerstand Herd",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homedata\")\r\n\t|> range(start: -72h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt.0.unterverteilung.herd.count_total\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n"
    }
   ]
  },
  {
   "title": "Power consumption over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"homedata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /alias[.]0[.]power[.](küche|herd)/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  "
    }
   ]
  }
 ]
}