{
 "title": "Shelly 3EM Pro Measurement",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Smart Counter",
   "type": "stat",
   "description": "Rebuild of the Smart counter value in the cellar of \"Am Rischbleek 40d\" based on the Shelly 3EM Pro installed nearby.\nCounter Reading  was 647 kWh on 29.12.2024",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "last_reading =\r\nfrom(bucket: \"homedata\")\r\n  |> range(start: -90d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alias.0.smartcounter.reading\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> last()\r\n  |> findRecord(idx:0, fn: (key) => true)\r\n\r\nt0 = last_reading._time\r\ncounter_offset= last_reading._value\r\n\r\n// using prefix \"m\" for _measurement here\r\nmGrid = \"shelly.0.shellypro3em#0cb815fd0400#1.EM0.TotalActivePower\"\r\n\r\nfrom(bucket: \"homedata\")\r\n  |> range(start: t0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] ==  mGrid)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> elapsed(columnName: \"dt\", unit: 1ms)\r\n  |> map(fn: (r) => ({ r with kiloWattHours:  if r._value > 0.0 then r._value * float(v:r.dt) / 3600000000.0 else 0.0 })) \r\n  |> drop(columns: [\"_value\", \"dt\"])\r\n  |> rename(columns: {kiloWattHours: \"_value\"})\r\n  |> sum()\r\n  |> map(fn: (r) => ({ r with _value: r._value + counter_offset }))\r\n"
    }
   ]
  },
  {
   "title": "Grid Power consumption",
   "type": "gauge",
   "description": "Displays the current power consumption from public grid of \"Am Rischbleek 40d\". Positive values mean that energy is pulled from public grid, negative values indicated delivery to the public grid.",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homedata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shelly.0.shellypro3em#0cb815fd0400#1.EM0.TotalActivePower\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar power generation",
   "type": "gauge",
   "description": "Displays the current power generation of the solar panels installed on garage roof of  \"Am Rischbleek 40d\". Positive values mean that energy is pulled from public grid, negative values indicated delivery to the public grid.",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homedata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt.0.solar.116183777340.0.power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "From Battery",
   "type": "gauge",
   "description": "Displays the current power generation of the solar panels installed on garage roof of  \"Am Rischbleek 40d\". Positive values mean that energy is pulled from public grid, negative values indicated delivery to the public grid.",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homedata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt.0.T2SGF72095.ACDISPLAY\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"BatSaldo\")"
    }
   ]
  },
  {
   "title": "Into Battery",
   "type": "gauge",
   "description": "Displays the current power generation of the solar panels installed on garage roof of  \"Am Rischbleek 40d\". Positive values mean that energy is pulled from public grid, negative values indicated delivery to the public grid.",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homedata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt.0.T2MG2CAA11.ACDISPLAY\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"BatSaldo\")"
    }
   ]
  },
  {
   "title": "Hourly power grid energy demand and total power consumption ",
   "type": "barchart",
   "description": "Grid Energy demand and Total Energy consumption  over the period indicated below.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nt0 = date.truncate(t: -24h, unit: 1h)\r\nt1 = now()\r\n\r\nfrom(bucket: \"homedata_reduced\")\r\n\t|> range(start: t0, stop: t1)\r\n\t|> filter(fn: (r) => r[\"_measurement\"] =~ /cachedEnergyData\\./)\r\n\t|> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n\t|> aggregateWindow(every: 1h, column: \"_value\", fn:first, timeSrc: \"_start\")\r\n\t|> difference(columns: [\"_value\"])\r\n\t|> timeShift(duration: -30m)\r\n\t|> drop(columns: [\"_start\", \"_stop\", \"_field\"])\r\n\t|> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n\t|> map (fn: (r) => ({\r\n\t\t\t\t\t\t\t_time: r._time, \r\n\t\t\t\t\t\t\ttoBatEnergy: -r[\"cachedEnergyData.toBatEnergy\"], \r\n\t\t\t\t\t\t\tfromBatEnergy: r[\"cachedEnergyData.fromBatEnergy\"], \r\n\t\t\t\t\t\t\tGridEnergyPos: r[\"cachedEnergyData.fromGridEnergy\"], \r\n\t\t\t\t\t\t\tGridEnergyNeg: -r[\"cachedEnergyData.toGridEnergy\"], \r\n\t\t\t\t\t\t\tSolarEnergy: r[\"cachedEnergyData.solarEnergy\"],\r\n\t\t\t\t\t\t}))\r\n\t|> map(fn: (r) => ({r with consumedEnergy: (r.GridEnergyPos + r.GridEnergyNeg + r.SolarEnergy + r.fromBatEnergy + r.toBatEnergy)}))\r\n\t|> sort(columns: [\"_time\"], desc: false)\r\n\t|> yield(name: \"result\")"
    }
   ]
  },
  {
   "title": "Daily Grid Demand Energy and Consumed Energy (Barchart)",
   "type": "barchart",
   "description": "Power consumption (positive) or generation (negative) over the period indicated below.",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nt0 = date.truncate(t: -28d, unit: 1d)\r\nt1 = v.timeRangeStop\r\n\r\nfrom(bucket: \"homedata_reduced\")\r\n\t|> range(start: t0, stop: t1)\r\n\t|> filter(fn: (r) => r[\"_measurement\"] =~ /cachedEnergyData\\./)\r\n\t|> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n\t|> aggregateWindow(every: 1d, column: \"_value\", fn:first, timeSrc: \"_start\")\r\n\t|> difference(columns: [\"_value\"])\r\n\t|> timeShift(duration: -12h)\r\n\t|> drop(columns: [\"_start\", \"_stop\", \"_field\"])\r\n\t|> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n\t|> map (fn: (r) => ({\r\n\t\t\t\t\t\t\t_time: r._time, \r\n\t\t\t\t\t\t\ttoBatEnergy: -r[\"cachedEnergyData.toBatEnergy\"], \r\n\t\t\t\t\t\t\tfromBatEnergy: r[\"cachedEnergyData.fromBatEnergy\"], \r\n\t\t\t\t\t\t\tGridEnergyPos: r[\"cachedEnergyData.fromGridEnergy\"], \r\n\t\t\t\t\t\t\tGridEnergyNeg: -r[\"cachedEnergyData.toGridEnergy\"], \r\n\t\t\t\t\t\t\tSolarEnergy: r[\"cachedEnergyData.solarEnergy\"],\r\n\t\t\t\t\t\t}))\r\n\t|> map(fn: (r) => ({r with consumedEnergy: (r.GridEnergyPos + r.GridEnergyNeg + r.SolarEnergy + r.fromBatEnergy + r.toBatEnergy)}))\r\n\t|> sort(columns: [\"_time\"], desc: false)\r\n\t|> yield(name: \"result\")"
    }
   ]
  },
  {
   "title": "Daily Grid Demand Energy and Consumed Energy",
   "type": "table",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Total Power consumption over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"homedata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shelly.0.shellypro3em#0cb815fd0400#1.EM0.TotalActivePower\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tapo Power Measurements",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"dict\"\r\nimport \"strings\"\r\n\r\ntapoDevice = (tapoId) => {\r\n    tapoDevices =\r\n        dict.fromList(\r\n            pairs: [\r\n                {key: \"8022150810927D9ECA0B3C3A1E79977D204A5418\", value: \"#3 Router/PC\"},\r\n                {key: \"8022413CC9E723E7FC057AD31EDD3D29206D1CBA\", value: \"#7 Pumpe Heizkreislauf\"},\r\n                {key: \"802244049CCDD7C0F17BC3D8862CA429204A698D\", value: \"#5 Geschirrspüler\"},\r\n                {key: \"802244430ABB337537E9507FE737DBF9204ABE4F\", value: \"#2 Kühlschrank\"},\r\n                {key: \"80225122541812548DCA6FAA73B86AF9204A11D5\", value: \"#4 Waschmaschine\"},\r\n                {key: \"8022AC1C757C4E11B13BFAE80F82534B206DD1CD\", value: \"#6 Gefrierschrank\"},\r\n                {key: \"8022CA342CADDC0889CA414B56ED977A1FA4EEA7\", value: \"#1 Fernseher\"},\r\n                {key: \"8022D37C06199EA87CF24F8B01449F10206DF8DB\", value: \"#8 Klimagerät\"},\r\n            ],\r\n        )\r\n    name = dict.get(dict: tapoDevices, key: tapoId, default: \"No known Tapo Device.\")\r\n\r\n    return name\r\n}\r\n\r\np110_devices = \r\nfrom(bucket: \"homedata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /tapo.0.[0-9A-Z]*.current/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 60s, fn: mean, createEmpty: true)\r\n  |> map(fn: (r) => ({r with _measurement: tapoDevice(tapoId: strings.substring(v:r._measurement, start:7, end:47)) }))\r\n\r\nunterverteilung_devices = \r\nfrom(bucket: \"homedata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /alias.0.power.(herd|küche)/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 60s, fn: mean, createEmpty: true)\r\n  |> movingAverage(n: 10)\r\n\r\nunion(tables: [p110_devices, unterverteilung_devices])\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])"
    }
   ]
  }
 ]
}